variables:
  CI_JOB_NAME: airflow-linting
  AIRFLOW_HOME: /builds/<folder_dir>
  AIRFLOW__CORE_dags_folder: /builds/<folder_dir>/dags/active/
  AIRFLOW_LOGGING_logging_level: WARNING

stages:
- build
- test

testing:
  stage: test

  image:
    name: apache/airflow:2.0.2-python3.7
    entrypoint: [""]
  before_script:
    - echo "Started job 'airflow-linter' - $(date)"
  script:
    - echo "beep"
  after_script:
    - echo "Finished job 'airflow-linter' - $(date)"
  allow_failure: true
